In [10]:
import ast
import argparse
import logging
from PIL import Image

import os
import numpy as np

# Duckietown Specific
from env import launch_env
from wrappers import NormalizeWrapper, ImgWrapper, \
  DtRewardWrapper, ActionWrapper, ResizeWrapper


In [5]:
env = launch_env()
print("Initialized environment")

# Wrappers
env = ResizeWrapper(env)
env = NormalizeWrapper(env)
env = ImgWrapper(env)  # to make the images from 160x120x3 into 3x160x120
env = ActionWrapper(env)
env = DtRewardWrapper(env)
print("Initialized Wrappers")

state_dim = env.observation_space.shape
action_dim = env.action_space.shape[0]
max_action = float(env.action_space.high[0])

total_timesteps = 0
timesteps_since_eval = 0
episode_num = 0
done = True
episode_reward = None
env_counter = 0
reward = 0
episode_timesteps = 0
obs = env.reset()

print(obs)


Initialized environment
Initialized Wrappers
[[[0.45098039 0.45098039 0.45098039 ... 0.45098039 0.45098039 0.45098039]
  [0.45098039 0.45098039 0.45098039 ... 0.45098039 0.45098039 0.45098039]
  [0.45098039 0.45098039 0.45098039 ... 0.45098039 0.45098039 0.45098039]
  ...
  [0.20784314 0.20784314 0.20784314 ... 0.15294118 0.15686275 0.15686275]
  [0.20784314 0.20784314 0.20784314 ... 0.15294118 0.15686275 0.15686275]
  [0.20784314 0.20784314 0.20784314 ... 0.15294118 0.15686275 0.15686275]]

 [[0.81960784 0.81960784 0.81960784 ... 0.81960784 0.81960784 0.81960784]
  [0.81960784 0.81960784 0.81960784 ... 0.81960784 0.81960784 0.81960784]
  [0.81960784 0.81960784 0.81960784 ... 0.81960784 0.81960784 0.81960784]
  ...
  [0.19607843 0.19607843 0.19607843 ... 0.14509804 0.14901961 0.15294118]
  [0.19607843 0.19607843 0.19607843 ... 0.14509804 0.14901961 0.15294118]
  [0.19607843 0.19607843 0.19607843 ... 0.14509804 0.14901961 0.15294118]]

 [[1.         1.         1.         ... 1.         

In [15]:
channel, h, w = obs.shape
data = np.transpose(obs, (0,1,2))
print(data.shape)
img = Image.fromarray(data, 'RGB')
img.show()

(3, 160, 120)


In [ ]:
while total_timesteps < 1:
    action = env.action_space.sample()
    # Perform action
    new_obs, reward, done, _ = env.step(action)

    obs = new_obs
    print(obs)
    
    total_timesteps += 1